### ISSUE TITLE
BE: create Python script to migrate pre-registrations from csv

### ISSUE THREAD

**Issue by ArJSarmiento** [SPARCS-UP-Mindanao/TechTix#268]
Create an `import_pre_registration_from_csv.py` file in `scripts` folder. 

use the `csv` Python library to read the contents of the CSV and write it to DynamoDB using `backend/repository/preregistrations_repository.py`.

Make sure to check the column names of the source CSV from GDG so that the script run smoothly on the actual google form schema. 

Inform Arnel if you are about to begin the task for AWS Credentials

**Comment by ArJSarmiento** [comment]
PR merged @ASPactores . Please do an end-to-end test on dev environment. Attach a recording to this ticket showing that it's functional with data  in dev environment. Show the CSV contents and the corresponding Pre-registrations generated in the admin website. Once done, please move ticket to Done. Thanks!

**Comment by ASPactores** [comment]
**Running Script:**
![Image](https://github.com/user-attachments/assets/6a342d0f-e5f1-4fd2-9797-063b4e4d416d)

**Sample CSV Content**
![Image](https://github.com/user-attachments/assets/3705303d-b4e4-4848-a967-db7245724d55)

**Generated Pre-registrations**
![Image](https://github.com/user-attachments/assets/55d0d6f0-e660-4864-8c98-7f20272dcbab)
