### ISSUE TITLE
BE: add platformFee Field in event POST, PUT, GET APIs

### ISSUE THREAD

**Issue by ArJSarmiento** [SPARCS-UP-Mindanao/TechTix#269]
Add a optional float `platformFee` field in Event (PynamoDB) and EventDBIn (Pydantic) models located in `backend/model/events/event.py`.

Deploy changes to dev and test if everything else is still working.

Attach a recording to this ticket after code approval as proof.

Inform Arnel if you are about to begin the task for AWS Credentials

**Comment by ArJSarmiento** [comment]
PR merged @44mira . Please do an end-to-end test on dev environment. Attach a recording to this ticket showing that Event APIs are still functional with the new features. Once done, please move ticket to Done. Thanks!

**Comment by 44mira** [comment]
https://github.com/user-attachments/assets/f7cca65f-0504-415f-b066-be69649b9a81
