### ISSUE TITLE
BE: add GDG Davao as a special email in the Events Service

### ISSUE THREAD

**Issue by ArJSarmiento** [SPARCS-UP-Mindanao/TechTix#270]
In `backend/usecase/email_usecase.py` add the GDG Davao email details in the `__sender_name_map`.

This makes sure that there will be no SPARCS related content in the emails sent.

Deploy changes to dev and test if everything else is still working.

Attach a recording to this ticket after code approval as proof.

**Inform Arnel if you are about to begin the task for AWS Credentials**

**Comment by ArJSarmiento** [comment]
PE merged @jcomrade . Please do an end-to-end test on dev environment. Attach a recording to this ticket that its functional. Once done, please move ticket to **Done**. Thanks!

**Comment by jcomrade** [comment]
https://github.com/user-attachments/assets/3c50199f-c20e-4960-b420-6ff5b2df1c58

**Comment by jcomrade** [comment]
https://github.com/user-attachments/assets/71aee9a7-69f8-4cd2-9261-4dcf02f9d088

Sampe event with random Konfhub Credentails

Expected output: No email recieved

**Comment by jcomrade** [comment]
https://github.com/user-attachments/assets/22250cbb-50bd-4061-9e48-996744105ac9

Sample Event creation using Special Email

Expected Output: Email Received without SPARCS related content in the email body
