### ISSUE TITLE
BE: add export as CSV API for registrations for Events Service

### ISSUE THREAD

**Issue by ArJSarmiento** [SPARCS-UP-Mindanao/TechTix#271]
In the `backend/controller/preregistration_router.py` and `backend/controller/registration_router.py`, add a GET `{eventId}/csv_download` API. This will use the `csv` python library in a usecase to read all of the current registrations or preregistrations and write the content into a CSV File,

- Write the file to an S3 Bucket and return the Pre-signed URL. 
- Use `tmpdir`
- Refer to `create_download_url` in `backend/usecase/file_s3_usecase.py`
- **Deploy changes to dev and test if everything else is still working.**
- Attach a recording to this ticket after code approval as proof.

**Inform Arnel if you are about to begin the task for AWS Credentials**

**Comment by ArJSarmiento** [comment]
PE merged @44mira  . Please do an end-to-end test on dev environment. Attach a recording to this ticket showing that it's functional with live APIs. **Show the CSV contents.**  Once done, please move ticket to Done. Thanks!

**Comment by 44mira** [comment]
https://github.com/user-attachments/assets/e88edd9e-a9f9-48b5-80a0-9f9f60af8c07

**Comment by ArJSarmiento** [comment]
Thanks @44mira! Ready for FE dev @seangaaab
